name: py_pinyin_txt CI/CD
on:
  push:
    branches:
      - "**"
  pull_request:
    types: [closed] 

jobs:
  test:
    name: Run all linters and tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      - run: pipenv run black .
      - run: pipenv run pylint py_pinyin_txt
      - run: pipenv run mypy py_pinyin_txt
      - run: pipenv run python -m unittest discover

  push_to_registry:
    name: Push Docker image to GitHub Packages
    needs: test
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Get the app version
        run: echo "APP_VERSION=$(cat VERSION)" >> $GITHUB_ENV
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: atomicmeganerd/py_pinyin_txt/py-pinyin-txt
          tags: ${{ env.APP_VERSION }},latest 
