name: py_pinyin_txt CI/CD
on:
  push:
    branches:
      - "master"
env:
  IMAGE_NAME: atomicmeganerd/py-pinyin-txt
jobs:
  run_tests_and_linters:
    name: Run all linters and tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      - run: pipenv run black .
      - run: pipenv run pylint py_pinyin_txt
      - run: pipenv run mypy py_pinyin_txt
      - run: pipenv run python -m unittest discover

  push_to_registry:
    name: Push Docker image to GitHub Packages
    needs: run_tests_and_linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Get the app version
        run: echo "APP_VERSION=$(cat VERSION)" >> $GITHUB_ENV
      - name: Login to the container registry
        uses: docker/login-action@v2
        with: 
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}/${{ env.APP_VERSION }},${{ env.IMAGE_NAME}}/latest 
